### ISSUE TITLE
Replace node tracking in the data file with the database

### ISSUE THREAD

**Issue by DanielOhrin** [DanielOhrin/minecraft-HSNodes#33]
Mark to be complete:
- [x] Can place and mine nodes just like before
- [x] Data file only tracks tasks
- [x] Code is readable, and the database class has relevant methods

**Comment by DanielOhrin** [comment]
Relevant methods could include:
database.placeNode --> Adds everything except the "mined" columns
database.mineNode --> Adds the remaining 3 values to the node,
