### ISSUE TITLE
Replace task tracking with the database

### ISSUE THREAD

**Issue by DanielOhrin** [DanielOhrin/minecraft-HSNodes#34]
Mark to be complete:
- [x] data.yml no longer exists
- [x] nodes still work as they did in 1.0
- [x] when you forcefully crash the server (close without saving), the node tasks are restarted and no functionality is lost

**Comment by DanielOhrin** [comment]
- [ ] Do some slight performance testing
